# Generated by Django 3.2.9 on 2021-11-22 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="default_profile_pic.png",
                        upload_to=users.models.get_upload_path,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                ("website", models.URLField(blank=True, default="")),
                (
                    "linkedin_user",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "facebook_user",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "github_user",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "youtube_user",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "twitter_user",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("author", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
