# Generated by Django 3.2.7 on 2021-09-22 11:54

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_profile_pic.png', upload_to=users.models.get_upload_path),
        ),
    ]
