# Generated by Django 3.2.10 on 2021-12-28 12:33

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                storage=users.models.OverwriteStorage(),
                upload_to=users.models.get_upload_path,
            ),
        ),
    ]
