# Generated by Django 3.2.7 on 2021-10-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_social_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='author',
            field=models.BooleanField(default=False),
        ),
    ]
