# Generated by Django 3.2.7 on 2021-10-29 17:22

import ckeditor.fields
import ckeditor_uploader.fields
import django.db.models.deletion
import django.db.models.manager
import hitcount.mixins
from django.conf import settings
from django.db import migrations, models

import blog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("preferences", "0003_alter_preferences_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("desc", models.CharField(max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", ckeditor_uploader.fields.RichTextUploadingField()),
                ("slug", models.SlugField(default="", unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=blog.models.OverwriteStorage(),
                        upload_to=blog.models.get_upload_path,
                    ),
                ),
                ("draft", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(models.Model, hitcount.mixins.HitCountModelMixin),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=15)),
                ("slug", models.SlugField(default="", unique=True)),
                ("posts", models.ManyToManyField(blank=True, to="blog.Blog")),
                (
                    "tag_creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SitePreferences",
            fields=[
                (
                    "preferences_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="preferences.preferences",
                    ),
                ),
                (
                    "sitename",
                    models.CharField(default="My Sexy Blog", max_length=50),
                ),
                ("title", models.CharField(default="My Blog", max_length=20)),
                (
                    "heading",
                    models.CharField(
                        default="A blog of blogging blogosity.", max_length=200
                    ),
                ),
                (
                    "pinned_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.blog",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Site Preferences",
            },
            bases=("preferences.preferences",),
            managers=[
                ("singleton", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by_guest",
                    models.CharField(blank=True, max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", ckeditor.fields.RichTextField()),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.blog",
                    ),
                ),
            ],
        ),
    ]
