# Generated by Django 3.2.12 on 2022-02-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='twitter_site',
            field=models.CharField(default='', max_length=50),
        ),
    ]
