# Generated by Django 3.2.9 on 2021-11-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_base_migrations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
    ]
