# Generated by Django 3.2.12 on 2022-02-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_sitepreferences_twitter_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_attrib_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_attrib_name_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_attrib_site',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_attrib_site_link',
            field=models.URLField(default=''),
        ),
    ]
