# Generated by Django 3.2.9 on 2021-11-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_guest_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_by_guest',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='guest_email',
            field=models.EmailField(max_length=254),
        ),
    ]
