# Generated by Django 3.2.12 on 2022-02-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220207_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_attrib_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_attrib_name_link',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_attrib_site',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_attrib_site_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
