# Generated by Django 3.2.7 on 2021-09-28 14:04

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210923_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
