# Generated by Django 3.2.7 on 2021-09-08 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_add_extra_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitepreferences',
            options={'verbose_name_plural': 'Site Preferences'},
        ),
    ]
