# Generated by Django 3.2.13 on 2022-06-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_series'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
    ]
