# Generated by Django 3.2.7 on 2021-09-30 10:30

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_created_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
