# Generated by Django 3.2.13 on 2022-06-07 15:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_series_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
