# Generated by Django 3.2.7 on 2021-10-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=15),
        ),
    ]
