# Generated by Django 3.2.7 on 2021-10-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20211012_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='posts',
            field=models.ManyToManyField(to='blog.Blog'),
        ),
    ]
