# Generated by Django 3.2.7 on 2021-10-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_tag_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='posts',
            field=models.ManyToManyField(null=True, to='blog.Blog'),
        ),
    ]
