# Generated by Django 3.2.7 on 2021-10-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_tag_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag_count',
        ),
        migrations.AlterField(
            model_name='tag',
            name='posts',
            field=models.ManyToManyField(blank=True, to='blog.Blog'),
        ),
    ]
