# Generated by Django 3.2.7 on 2021-10-17 10:43

from django.db import migrations, models

import blog.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_tag_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                null=True, upload_to=blog.models.get_upload_path
            ),
        ),
    ]
