# Generated by Django 3.2.7 on 2021-10-17 15:42

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=blog.models.OverwriteStorage(), upload_to=blog.models.get_upload_path),
        ),
    ]
