# Generated by Django 3.2.7 on 2021-10-23 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='pinned_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
    ]
