"""Django settings for pyBlog project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv(override=True)  # loads the configs from .env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read the SECRET_KEY from the .env file
SECRET_KEY = str(os.getenv("SECRET_KEY"))

# Set DEBUG from the .env file
DEBUG = bool(int(os.getenv("DEBUG", 0)))

# Add extra hosts from the .env file if specified
EXTRA_HOSTS = list(filter(None, str(os.getenv("ALLOWED_HOSTS", "")).split(",")))
ALLOWED_HOSTS = ["localhost", "127.0.0.1"] + EXTRA_HOSTS

# Application definition
INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "user_sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "django.contrib.humanize",
    "preferences",
    "rundevserver",
    "compressor",
    "django.forms",
    "django_gravatar",
    "dj_pagination",
    "maintenance_mode",
    "secretballot",
    "django_recaptcha",
    "likes",
    "blog",
    "users",
    "hitcount",
    "django_ckeditor_5",
]


# only include the Admin paths if we are in DEBUG mode
if DEBUG:
    INSTALLED_APPS = ["pyblog.apps.MyAdminConfig"] + INSTALLED_APPS

# Change this IF needed AND running the server behind a proxy.
FIX_PROXY_IP = bool(int(os.getenv("FIX_PROXY_IP", "0")))


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # "django.contrib.sessions.middleware.SessionMiddleware",
    "user_sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "maintenance_mode.middleware.MaintenanceModeMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "dj_pagination.middleware.PaginationMiddleware",
    "likes.middleware.SecretBallotUserIpUseragentMiddleware",
    # "htmlmin.middleware.MarkRequestMiddleware",
]

# Only load the XForwarded fix if explicitly required
if FIX_PROXY_IP:
    MIDDLEWARE = [
        "x_forwarded_for.middleware.XForwardedForMiddleware"
    ] + MIDDLEWARE


# configure the user_sessions engine
SESSION_ENGINE = "user_sessions.backends.db"
# silence the warning about the session engine, we have a third party one.
SILENCED_SYSTEM_CHECKS = ["admin.E410"]

# location of GeoIP data
GEOIP_PATH = BASE_DIR / "geoip"

ROOT_URLCONF = "pyblog.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "maintenance_mode.context_processors.maintenance_mode",
                "django.contrib.messages.context_processors.messages",
                "preferences.context_processors.preferences_cp",
            ],
        },
    },
]

WSGI_APPLICATION = "pyblog.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": str(os.getenv("BLOG_DB_NAME")),
        "USER": str(os.getenv("BLOG_DB_USER")),
        "PASSWORD": str(os.getenv("BLOG_DB_PASSWORD")),
        "HOST": str(os.getenv("BLOG_DB_HOST")),
        "PORT": str(os.getenv("BLOG_DB_PORT")),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Setup Email backend
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = str(os.getenv("EMAIL_HOST"))
EMAIL_PORT = str(os.getenv("EMAIL_PORT"))
EMAIL_USE_TLS = str(os.getenv("EMAIL_USE_TLS"))
EMAIL_HOST_USER = str(os.getenv("EMAIL_HOST_USER"))
EMAIL_HOST_PASSWORD = str(os.getenv("EMAIL_HOST_PASSWORD"))
DEFAULT_FROM_EMAIL = str(os.getenv("EMAIL_FROM"))

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-gb"

TIME_ZONE = "Europe/London"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = "static"

STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "compressor.finders.CompressorFinder",
)


MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = "blog:index"
LOGOUT_REDIRECT_URL = "blog:index"
LOGIN_URL = "login"

X_FRAME_OPTIONS = "SAMEORIGIN"

# settings for the dj-pagination application.
PAGINATION_DISPLAY_DISABLED_PREVIOUS_LINK = True
PAGINATION_DISPLAY_DISABLED_NEXT_LINK = True
PAGINATION_DEFAULT_WINDOW = 1
PAGINATION_DEFAULT_MARGIN = 0
PAGINATION_INVALID_PAGE_RAISES_404 = True
PAGINATION_DISABLE_LINK_FOR_FIRST_PAGE = True

# settings for dh-hitcount application
HITCOUNT_HITS_PER_IP_LIMIT = 0
HITCOUNT_USE_IP = True

# settings for CKEditor Rich-text editor plugin
CKEDITOR_UPLOAD_PATH = "image/uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_ALLOW_NONIMAGE_FILES = False
CKEDITOR_BROWSE_SHOW_DIRS = True
CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_CONFIGS = {
    "default": {},
    "post": {
        "width": "auto",
        "height": "450px",
        "tabSpaces": 4,
        "toolbar": "Custom",
        "toolbar_Custom": [
            ["CodeSnippet"],
            ["Format"],
            [
                "Bold",
                "Italic",
                "Underline",
                "Strike",
                "RemoveFormat",
                "Blockquote",
            ],
            [
                "JustifyLeft",
                "JustifyCenter",
                "JustifyRight",
                "JustifyBlock",
            ],
            ["Smiley", "SpecialChar"],
            ["TextColor", "BGColor"],
            ["Image"],
            ["Link", "Unlink"],
            ["Table", "HorizontalRule"],
            ["NumberedList", "BulletedList"],
            ["Maximize"],
            ["Preview"],
        ],
        "removePlugins": "exportpdf",
        "extraPlugins": ",".join(
            [
                "codesnippet",
                "prism",
                "widget",
                "lineutils",
            ]
        ),
        "format_tags": "p;h2;h3;h4;pre;address;div",
        "editorplaceholder": "Start typing something great!",
    },
    "comment": {
        "width": "auto",
        "height": "450px",
        "tabSpaces": 4,
        "toolbar": "Custom",
        "toolbar_Custom": [
            ["CodeSnippet"],
            ["Format"],
            [
                "Bold",
                "Italic",
                "Underline",
                "Strike",
                "RemoveFormat",
                "Blockquote",
            ],
            ["Smiley", "SpecialChar"],
            ["TextColor"],
            ["Link", "Unlink"],
            ["Table", "HorizontalRule"],
            ["NumberedList", "BulletedList"],
            ["Maximize"],
            ["Preview"],
        ],
        "removePlugins": "exportpdf",
        "extraPlugins": ",".join(
            [
                "codesnippet",
                "prism",
                "widget",
                "lineutils",
            ]
        ),
        "format_tags": "p;h2;h3;h4;pre;address;div",
        "editorplaceholder": "Enter your Comment. Please be polite and thoughtful to others.",
    },
}

# Secret Ballot settings.
SECRETBALLOT_FOR_MODELS:dict[str,dict] = {
    "blog.Blog": {},
}

# Settings for the maintenance_mode plugin
MAINTENANCE_MODE_IGNORE_STAFF = True
MAINTENANCE_MODE_IGNORE_SUPERUSER = True

# recapcha settings
RECAPTCHA_PUBLIC_KEY = str(os.getenv("RECAPTCHA_PUBLIC_KEY"))
RECAPTCHA_PRIVATE_KEY = str(os.getenv("RECAPTCHA_PRIVATE_KEY"))

# rundevserver settings
RDS_ALL_INTERFACES = True
RDS_DEBUG = True


customColorPalette = [
        {
            'color': 'hsl(4, 90%, 58%)',
            'label': 'Red'
        },
        {
            'color': 'hsl(340, 82%, 52%)',
            'label': 'Pink'
        },
        {
            'color': 'hsl(291, 64%, 42%)',
            'label': 'Purple'
        },
        {
            'color': 'hsl(262, 52%, 47%)',
            'label': 'Deep Purple'
        },
        {
            'color': 'hsl(231, 48%, 48%)',
            'label': 'Indigo'
        },
        {
            'color': 'hsl(207, 90%, 54%)',
            'label': 'Blue'
        },
    ]

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link',
                    'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', ],

    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': ['heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
        'code','subscript', 'superscript', 'highlight', '|', 'codeBlock', 'sourceEditing', 'insertImage',
                    'bulletedList', 'numberedList', 'todoList', '|',  'blockQuote', 'imageUpload', '|',
                    'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed', 'removeFormat',
                    'insertTable',],
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                        'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side',  '|'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]

        },
        'table': {
            'contentToolbar': [ 'tableColumn', 'tableRow', 'mergeTableCells',
            'tableProperties', 'tableCellProperties' ],
            'tableProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            },
            'tableCellProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            }
        },
        'heading' : {
            'options': [
                { 'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph' },
                { 'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1' },
                { 'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2' },
                { 'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3' }
            ]
        }
    },
    'list': {
        'properties': {
            'styles': 'true',
            'startIndex': 'true',
            'reversed': 'true',
        }
    }
}

# Define a constant in settings.py to specify file upload permissions
CKEDITOR_5_FILE_UPLOAD_PERMISSION = "authenticated"  # Possible values: "staff", "authenticated", "any"
